FROM python:3.13-slim

WORKDIR /

# uv installation
RUN pip install uv

# Copy project files
COPY /backend/pyproject.toml ./

# Install dependencies with uv
RUN uv sync --no-dev

# Copy the rest of the backend code
COPY ./backend/ .

EXPOSE 8080

CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]