"""Shared MongoDB client configuration.

Single source of truth for the Atlas application name. Keep this here rather than
inline at each MongoClient call: connection strings copied from the Atlas UI, and
snippets generated by LLMs, routinely drop the appName option, which silently
breaks observability and content attribution for this demo.

Naming convention: devrel-MEDIUM-PRIMARY-SECONDARY-OPTIONAL
"""

APP_NAME = "devrel-github-python-credit-scoring-langchain"
