//'use client'
import React from 'react';
import { useState } from "react";

import styles from '../styles/header.module.css';
import { MongoDBLogoMark } from '@leafygreen-ui/logo';
import { H2, Body } from '@leafygreen-ui/typography';
//import Link from 'next/link';
import InfoWizard from "./InfoWizard/InfoWizard";


function Header() {
  const [openHelpModal, setOpenHelpModal] = useState(false);

  return (
    <div className={styles["layout-header"]}>
      <div className={styles["logo-container"]}>
        <MongoDBLogoMark />
      </div>
      <div className={styles["title-container"]}>
        <H2>Credit Scoring</H2>
      </div>
      <div className={styles["logout-container"]}>

        <InfoWizard
          open={openHelpModal}
          setOpen={setOpenHelpModal}
          tooltipText="Tell me more!"
          iconGlyph="Wizard"
          sections={[
            {
              heading: "Instructions and Talk Track",
              content: [
                {
                  heading: "Demo Purpose",
                  body: "The purpose of this demo is to illustrate how one can improve the customers’ experience in a credit card application process through the innovative use of predictive and generative AI.",
                },
                {
                  heading: "How to Use the Demo",
                  body: [
                    "On the left hand panel, adjust the factors with the respective sliders, to explore the impact of changing the factors to Credit Health Status",
                    "Click on 'Save Profile'",
                    "Note that the application actually derives a credit score behind the scenes but for simplicity, it only displays a Credit Health Status to indicate the status of the credit card application, that is, Approved or Rejected",
                    "On the right panel of the demo below the Credit Health Status, it shows the explanation generated by GenAI based on the results of credit score and also the risk factors impacting the credit score",
                    "The “Product recommendations” tab, powered by Generative AI, suggests alternative credit card products tailored to the credit profile. This feature assists rejected applicants with alternative options and provides cross-sell opportunities for approved customers.",
                  ],
                },
              ],
            },
            {
              heading: "Behind the Scenes",
              content: [
                {
                  heading: "Data Flow",
                  body: "",
                },
                {
                  image: {
                    src: "./images/info.png",
                    alt: "Architecture",
                  },
                },
              ],
            },
            {
              heading: "Why MongoDB?",
              content: [
                {
                  heading: "MongoDB Atlas Vector Search",
                  body: "This feature  enables semantic search and generative AI across diverse data within a single, unified platform. It seamlessly integrates operational database features with vector search through a native MongoDB interface. Users can create vector embeddings using machine learning models, storing and indexing them in MongoDB Atlas for applications like retrieval-augmented generation (RAG), semantic search, recommendation engines, and dynamic personalization.",
                },
                {
                  heading: "Operational Data Store (ODS) Capabilities",
                  body: "MongoDB is ideal as an ODS for storing dynamic credit card product data. Its flexible schema and powerful update capabilities can handle the frequent changes in product offerings, benefits, and fee structures. This makes it easy for financial institutions to manage large datasets, enabling real-time data updates and seamless product modifications.",
                },
                {
                  heading: "Vector Indexing",
                  body: "MongoDB's support for vector indexing is particularly advantageous for working with product descriptions. Credit card product descriptions can be extensive, so breaking them into smaller, manageable chunks aids in efficient retrieval and analysis. Using MongoDB's vector indexes, you can build streamlined pathways to access and analyze product data, enabling rapid response times for recommendation engines.",
                },
              ],
            },
          ]}
        />
      </div>
    </div>

  );
}

export default Header;

